/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Simple function to test the binding */
export declare function helloWorld(): string
/** Get library version */
export declare function getVersion(): string
